name: Vercel Preview Deployment

on:
  push:
    branches-ignore:
      - main

jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Trigger Vercel Preview Deploy Hook
        run: |
          curl -X POST -fsS ${{ secrets.VERCEL_PREVIEW_HOOK }}
